### ISSUE TITLE
Runtime properties not works

### ISSUE THREAD

**Issue by masalinas** [bijukunjummen/cf-db-services-sample#2]
I was checking the deployment  option of properties but not works. I'll explain it:

I have two deployments files for the Spring Boot like you:

**application.yml:**

```
---
info:
  app:
    description: Cloud Foundry MySQL Service Training
    name: training.cf.services
    version: 0.0.1-SNAPSHOT
    
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    beans:
      enabled: true            
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health, beans
        
server:
  port: 3000
  
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trainingdb?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: thingtrack
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
```

**and the other is application-cloud.yml**

```
---
management:            
  endpoints:
    enabled-by-default: false

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: ${vcap.services.training-db-service.credentials.jdbcUrl}
    username: ${vcap.services.training-db-service.credentials.username}
    password: ${vcap.services.training-db-service.credentials.password}
```

That you see in the first deployment file I enabled some spring boot endpoints, but in the cloud deployment not. The cloud foundry manifest used to deploy in my pivotal webservice is:

```
---
applications:
- name: training.cf.services
  path: target/training.cf.services-0.0.1-SNAPSHOT.jar
  instances: 1
  memory: 1024M  
  services:
  - training-db-service
  env:
    SPRING_PROFILES_ACTIVE: cloud  
    
buildpack: https://github.com/cloudfoundry/java-buildpack.git

env:
  JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{enabled: false}'
```

My App deployed correctly in my space account in Pivotal, but the endpoints are enabled (for example the beans) and it must be inpossible, because the Spring Boot deployment application-cloud.yml desable then. This test tell me that the JBP_CONFIG_SPRING_AUTO_RECONFIGURATION not works I think

Then, What happend?

Regards
